name: Hello Github Actions
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      COURSE: CloudComputing
    steps:
      - run: echo "Hello from Github Actions!"
      - run: echo "I'll list files."
      - run: ls -al
    
